# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Covariance matrix of Matern GP
#'
#' This function evaluates the covariance matrix of Matern GP using the coordinates.
#'
#' @param X1 arma::mat, each row representing the coordiantes of a location
#' @param X2 arma::mat, each row representing the coordiantes of a location
#' @param nu double, the smoothness of the Matern process
#' @param tau double, the time rescaling parameter of the Matern process
#' @param s double, the space rescaling parameter of the Matern process. Currently set as 1
#' @return the computed covariance matrix.
#' @useDynLib GPDAG, .registration = TRUE
#' @export
cov_matern <- function(X1, X2, nu = 3/2, tau = 1, s = 1) {
    .Call(`_GPDAG_cov_matern`, X1, X2, nu, tau, s)
}

#' Covariance matrix of GP with Gaussian Kernel
#'
#' This function evaluates the covariance matrix of GP with Gaussian Kernel using the coordinates.
#'
#' @param X1 arma::mat, each row representing the coordiantes of a location
#' @param X2 arma::mat, each row representing the coordiantes of a location
#' @param tau double, the time rescaling parameter of the GP
#' @param s double, the space rescaling parameter of the GP. Currently set as 1
#' @return the computed covariance matrix.
#' @useDynLib GPDAG, .registration = TRUE
#' @export
cov_gaussian <- function(X1, X2, tau = 1, s = 1) {
    .Call(`_GPDAG_cov_gaussian`, X1, X2, tau, s)
}

#' Cholesky of DAG GP covariance matrix
#'
#' This function performs Cholesky decomposition of DAG GP covariance function. No input of the whole covariance matrix is
#' needed. Instead, this function will call evaluate the covariance matrix based on the DAG structure.
#'
#' @param X arma::mat, with each row representing the coordiante of a location
#' @param dag arma::field<arma::uvec>, each entry contains the indices of its parent sets in DAG ordering
#' @param nu double, the smoothness of the Matern process
#' @param tau double, rescaling parameter of the Matern process
#' @param tol double, in case of numerical singularity (negative conditional variance), set the conditional variance as tol
#' @return Rcpp list consists of two entries, L and D, such that L D^{-1} L^T is the precision matrix.
#' D is the conditonal variance for ith element, while the off-diagonal elements of L[,i] are negative conditional regression coefficients of ith elements on its parents.
#' @useDynLib GPDAG, .registration = TRUE
#' @export
DAG_Chol <- function(X, dag, nu = 3/2, tau = 1, s = 1, cov_type = "matern", tol = 2e-16) {
    .Call(`_GPDAG_DAG_Chol`, X, dag, nu, tau, s, cov_type, tol)
}

#' MCMC for DAG GP
#'
#' This is the advanced function to perform MCMC for DAG GP and works for generic training set and DAG structures. For implementation on grid, one can call GPgrid instead.
#' This functions takes the coordinates of training locations (X), the DAG (dag) and the response (Y) as input. It performs MCMC and return
#' the MCMC samples as output. It uses a Gibbs sampler framework, whiling calling preconditioner Conjugate gradient when sampling latent process values.
#'
#' @param X arma::mat, with each row representing the coordiante of a location
#' @param dag arma::field<arma::uvec>, each entry contains the indices of its parent sets in DAG ordering
#' @param log_tau_prior_fun Function,log prior function for tau
#' @param tau_bound arma::vec, lower and upper bounds for tau
#' @param nug_prior arma::vec, parameters for inverse gamma prior for sigma^2
#' @param sig_bound arma::vec, lower and upper bounds for sigma, currently not used in the codes
#' @param nu double, the smoothness of the Matern process
#' @param tau double, initial value for rescaling parameter of the Matern process
#' @param sig double, initial value for the standard deviation of nugget effects
#' @param n_mcmc unsigned integer, number of MCMC iterations
#' @param n_burn unsigned integer, number of MCMC iterations that are burnt
#' @param tol double, the tolerance of squared l2 norm of conjugate gradient
#' @param maxcgiter unsigned int, the maximal number of conjugate gradient iterations
#' @return Rcpp list consists results of MCMC:
#'         tau_mcmc, the MCMC samples of tau;
#'         sig_mcmc, the MCMC samples of sig;
#'         sig2_mean_mcmc, the mean value of sigma squared in each MCMC iteration;
#'         Z_mcmc, a matrix, each row contains the MCMC sample of the latent function in that iteration;
#'         Accept_ratio, average acceptance ratio for sampling the rescaling paramter tau. Is irrelevant if not in a hierarchical Bayes framework;
#'         L & D, the ouput of function DAG_Chol in the last MCMC iterations;
#'         RunTime: the total real world running time of the MCMC;
#'         CG_iters: the number of conjuate gradient iterations for each MCMC step;
#'         CG_err: the conjugate gradient error for each MCMC step.
#' @useDynLib GPDAG, .registration = TRUE
#' @export
mcmc <- function(X, dag, Y, log_tau_prior_fun, tau_bound, nug_prior, sig_bound, nu = 3/2, tau = 1, sig = 0.1, s = 1, cov_type = "matern", n_mcmc = 4000L, n_burn = 2000L, tol = 1e-12, maxcgiter = 400L) {
    .Call(`_GPDAG_mcmc`, X, dag, Y, log_tau_prior_fun, tau_bound, nug_prior, sig_bound, nu, tau, sig, s, cov_type, n_mcmc, n_burn, tol, maxcgiter)
}

